merge Release/live service/55.1 into master
SkillsFundingAgency/dfc-app-jobgroups pull request #126
Opened 2024-04-12 14:28 UTC by JessiePotter1

2024-04-17 12:03 UTC, hnandra commented on DFC.App.JobGroups.Services.CacheContentService/SharedContentCacheReloadService.cs
> +        //private readonly IDocumentService<ContentItemModel> contentItemDocumentService;
Delete comment

2024-04-17 12:12 UTC, hnandra requested changes
Delete comments

2024-04-17 12:12 UTC, hnandra commented on DFC.App.JobGroups/Controllers/PagesController.cs
> +        //public const string SharedContentStaxId = "2c9da1b3-3529-4834-afc9-9cd741e59788";
Delete comment

2024-04-17 12:40 UTC, hnandra approved these changes, later dismissed

2024-04-17 14:01 UTC, gcomptonedu submitted a review, later dismissed
Reviewed

2024-04-23 11:53 UTC, ZhaomingLu2009 approved these changes

2024-04-23 11:55 UTC, hnandra approved these changes

2024-04-23 11:55 UTC, gcomptonedu approved these changes
Reviewed

2024-04-23 11:57 UTC, merged